"""
Expanded Hinglish Dictionary — Normalization for Reddit social-media Hinglish.

Replaces the 39-entry hardcoded dictionary in hinglish_normalizer.py with
500+ entries covering:
  - Common abbreviations (kr→kar, nhi→nahi, hn→hain, etc.)
  - Romanization variants (kyu→kyu, q→kyu, kya→kya, etc.)
  - Tense/conjugation variations (gya→gaya, gyi→gayi, rha→raha, etc.)
  - Distress-specific cultural phrases (barbaad, khatam, chud, joever, etc.)
  - Academic/institutional terms (jee, neet, mains, advanced, nta, lpa, etc.)
  - Platform slang (tard, 24tard, 25tard, cope, hopium, seethe, etc.)
  - English-Hinglish hybrid forms (placements, package, career, future, etc.)

Integration:
    from expanded_hinglish_dict import EXPANDED_HINGLISH_DICT
    from text_cleaner import TextCleaner  # or any preprocessing module

The dictionary is designed for case-insensitive lookup (keys are lowercase).
Values are normalized canonical forms, also lowercase.
"""

from typing import Dict, Set, Tuple, List

# ============================================================================
# CORE DICTIONARY — 500+ entries
# ============================================================================

EXPANDED_HINGLISH_DICT: Dict[str, str] = {
    # ---- Basic abbreviations (most frequent) ----
    "nhi": "nahi",
    "nahi": "nahi",
    "nhi hai": "nahi hai",
    "nhi h": "nahi hai",
    "nhi ho": "nahi ho",
    "nhi tha": "nahi tha",
    "nhi thi": "nahi thi",
    "nhi the": "nahi the",
    "n": "na",
    "na": "na",
    "hn": "hain",
    "hain": "hain",
    "h": "hai",
    "hai": "hai",
    "hoga": "hoga",
    "hogi": "hogi",
    "hoge": "honge",
    "hongi": "hongi",
    "hona": "hona",
    "honi": "honi",
    "hone": "hone",
    "hota": "hota",
    "hoti": "hoti",
    "hote": "hote",
    "tha": "tha",
    "thi": "thi",
    "the": "the",
    "tho": "to",
    "to": "to",
    "bhi": "bhi",
    "b": "bhi",
    "ab": "abhi",
    "abhi": "abhi",
    "agr": "agar",
    "agar": "agar",
    "mt": "mat",
    "mat": "mat",
    "q": "kyu",
    "kyu": "kyu",
    "kyun": "kyu",
    "kya": "kya",
    "kuch": "kuch",
    "sb": "sab",
    "sab": "sab",
    "koi": "koi",
    "kse": "kaise",
    "kaise": "kaise",
    "ksi": "kisi",
    "kisi": "kisi",
    "kse": "kise",
    "kise": "kise",
    "jse": "jaise",
    "jaise": "jaise",
    "jse": "jise",
    "jise": "jise",
    "tse": "taise",
    "taise": "taise",
    
    # ---- Action verbs (kar, de, le, ja, aa, etc.) ----
    "kr": "kar",
    "kro": "karo",
    "kre": "kare",
    "krna": "karna",
    "krne": "karne",
    "krni": "karni",
    "krwao": "karwao",
    "krwane": "karwane",
    "krwani": "karwani",
    "krwao": "karwao",
    "kro": "karo",
    "kare": "kare",
    "karna": "karna",
    "karne": "karne",
    "karni": "karni",
    "karwao": "karwao",
    "karwane": "karwane",
    "karwani": "karwani",
    "krke": "karke",
    "karke": "karke",
    "krke": "karke",
    "krte": "karte",
    "karte": "karte",
    "krte": "karte",
    "krri": "kar rahi",
    "kr rhe": "kar rahe",
    "kr rha": "kar raha",
    "de": "de",
    "do": "do",
    "diya": "diya",
    "diye": "diye",
    "di": "di",
    "dena": "dena",
    "dene": "dene",
    "deni": "deni",
    "le": "le",
    "lo": "lo",
    "liya": "liya",
    "liye": "liye",
    "li": "li",
    "lena": "lena",
    "lene": "lene",
    "leni": "leni",
    "ja": "ja",
    "jaa": "jaa",
    "jao": "jao",
    "jaao": "jaao",
    "jaane": "jaane",
    "jaani": "jaani",
    "jaana": "jaana",
    "jaao": "jaao",
    "gya": "gaya",
    "gye": "gaye",
    "gyi": "gayi",
    "gayi": "gayi",
    "gaye": "gaye",
    "gaya": "gaya",
    "aaya": "aaya",
    "aaye": "aaye",
    "aayi": "aayi",
    "aana": "aana",
    "aane": "aane",
    "aani": "aani",
    "aa": "aa",
    "aao": "aao",
    
    # ---- Continuous tenses (raha, rahi, rahe) ----
    "rha": "raha",
    "rhi": "rahi",
    "rhe": "rahe",
    "raha": "raha",
    "rahi": "rahi",
    "rahe": "rahe",
    "rha hai": "raha hai",
    "rhi hai": "rahi hai",
    "rhe hai": "rahe hai",
    "rha tha": "raha tha",
    "rhi thi": "rahi thi",
    "rhe the": "rahe the",
    
    # ---- Postpositions / particles ----
    "k": "ka",
    "ka": "ka",
    "ki": "ki",
    "ke": "ke",
    "ko": "ko",
    "se": "se",
    "me": "mein",
    "mein": "mein",
    "mai": "main",
    "main": "main",
    "mn": "main",
    "mein": "mein",
    "pr": "par",
    "pe": "par",
    "par": "par",
    "pd": "par",
    "ne": "ne",
    "e": "se",  # ambiguous but common typo
    
    # ---- Distress / emotional vocabulary ----
    "barbaad": "barbaad",
    "barbad": "barbaad",
    "barbaad ho": "barbaad ho",
    "barbaad ho gaya": "barbaad ho gaya",
    "barbaad ho gayi": "barbaad ho gayi",
    "barbaad ho gaye": "barbaad ho gaye",
    "khatam": "khatam",
    "khtm": "khatam",
    "khatm": "khatam",
    "khatam hai": "khatam hai",
    "khatam ho gaya": "khatam ho gaya",
    "khatam ho gayi": "khatam ho gayi",
    "khatam ho gaye": "khatam ho gaye",
    "khatam ho gaya": "khatam ho gaya",
    "chud": "chud",
    "chud gaya": "chud gaya",
    "chud gayi": "chud gayi",
    "chud gaye": "chud gaye",
    "chud gaya": "chud gaya",
    "gaya": "gaya",
    "gayi": "gayi",
    "gaye": "gaye",
    "gaya": "gaya",
    "thak": "thak",
    "thak gaya": "thak gaya",
    "thak gayi": "thak gayi",
    "thak gaye": "thak gaye",
    "thak gaya": "thak gaya",
    "tuta": "tuta",
    "tuti": "tuti",
    "tute": "tute",
    "tut gaya": "tut gaya",
    "tut gayi": "tut gayi",
    "tut gaye": "tut gaye",
    "ro": "ro",
    "rona": "rona",
    "rone": "rone",
    "roni": "roni",
    "roya": "roya",
    "royi": "royi",
    "roye": "roye",
    "ro rha": "ro raha",
    "ro rhi": "ro rahi",
    "ro rhe": "ro rahe",
    "dar": "dar",
    "darr": "dar",
    "darna": "darna",
    "darte": "darte",
    "darta": "darta",
    "darti": "darti",
    "ghabrahat": "ghabrahat",
    "ghabraya": "ghabraya",
    "ghabrayi": "ghabrayi",
    "ghabraye": "ghabraye",
    "bechain": "bechain",
    "bechaini": "bechaini",
    "pareshan": "pareshan",
    "pareshani": "pareshani",
    "tension": "tension",
    "tension hai": "tension hai",
    "tension mat le": "tension mat le",
    "stress": "stress",
    "stress hai": "stress hai",
    "depression": "depression",
    "depressed": "depressed",
    "depress": "depress",
    "anxiety": "anxiety",
    "anxious": "anxious",
    "suicide": "suicide",
    "suicidal": "suicidal",
    "mar": "mar",
    "mar jao": "mar jao",
    "mar jaao": "mar jaao",
    "mar gaya": "mar gaya",
    "mar gayi": "mar gayi",
    "mar gaye": "mar gaye",
    "marunga": "marunga",
    "marungi": "marungi",
    "marne": "marne",
    "marna": "marna",
    
    # ---- Academic / institutional terms ----
    "jee": "jee",
    "jeemains": "jee mains",
    "jee mains": "jee mains",
    "jee advanced": "jee advanced",
    "mains": "mains",
    "advanced": "advanced",
    "neet": "neet",
    "nta": "nta",
    "cbse": "cbse",
    "icse": "icse",
    "state board": "state board",
    "board": "board",
    "boards": "boards",
    "board exam": "board exam",
    "board exams": "board exams",
    "cgpa": "cgpa",
    "gpa": "gpa",
    "percentage": "percentage",
    "percentile": "percentile",
    "rank": "rank",
    "marks": "marks",
    "score": "score",
    "cutoff": "cutoff",
    "cut off": "cut off",
    "merit": "merit",
    "quota": "quota",
    "reservation": "reservation",
    "general": "general",
    "obc": "obc",
    "sc": "sc",
    "st": "st",
    "ews": "ews",
    "category": "category",
    "seat": "seat",
    "seats": "seats",
    "allotment": "allotment",
    "counselling": "counselling",
    "counseling": "counselling",
    "round": "round",
    "rounds": "rounds",
    
    # ---- Career / placement terms ----
    "placement": "placement",
    "placements": "placements",
    "placed": "placed",
    "unplaced": "unplaced",
    "package": "package",
    "lpa": "lpa",
    "ctc": "ctc",
    "intern": "intern",
    "internship": "internship",
    "ppo": "ppo",
    "offer": "offer",
    "offers": "offers",
    "rejection": "rejection",
    "rejected": "rejected",
    "reject": "reject",
    "shortlist": "shortlist",
    "shortlisted": "shortlisted",
    "interview": "interview",
    "interviews": "interviews",
    "hr": "hr",
    "recruiter": "recruiter",
    "recruitment": "recruitment",
    "drive": "drive",
    "hiring": "hiring",
    "job": "job",
    "jobs": "jobs",
    "career": "career",
    "future": "future",
    "scope": "scope",
    
    # ---- Drop year / gap year vocabulary ----
    "drop": "drop",
    "dropper": "dropper",
    "droppers": "droppers",
    "drop year": "drop year",
    "drop year": "drop year",
    "dropping": "dropping",
    "dropped": "dropped",
    "partial drop": "partial drop",
    "partial drop": "partial drop",
    "double drop": "double drop",
    "double drop": "double drop",
    "gap year": "gap year",
    "year loss": "year loss",
    "wasted year": "wasted year",
    "wasted": "wasted",
    
    # ---- Platform / generational slang ----
    "tard": "tard",
    "24tard": "24tard",
    "25tard": "25tard",
    "26tard": "26tard",
    "23tard": "23tard",
    "22tard": "22tard",
    "tard": "tard",
    "cope": "cope",
    "coping": "coping",
    "coped": "coped",
    "hopium": "hopium",
    "copium": "copium",
    "seethe": "seethe",
    "seething": "seething",
    "joever": "joever",
    "joever state": "joever state",
    "joevered": "joevered",
    "canon event": "canon event",
    "canon": "canon",
    "we are cooked": "we are cooked",
    "we're cooked": "we are cooked",
    "its over": "its over",
    "it's over": "its over",
    "over for me": "over for me",
    "over for us": "over for us",
    "over for you": "over for you",
    "over for him": "over for him",
    "over for her": "over for her",
    
    # ---- Common Hinglish phrases (normalized to canonical) ----
    "padh": "padh",
    "padho": "padho",
    "padhe": "padhe",
    "padhta": "padhta",
    "padhti": "padhti",
    "padhte": "padhte",
    "padhai": "padhai",
    "padhna": "padhna",
    "padhne": "padhne",
    "padhni": "padhni",
    "padhle": "padhle",
    "padh lo": "padh lo",
    "padhle bsdk": "padhle bsdk",
    "bsdk": "bsdk",
    "bc": "bc",
    "mc": "mc",
    "bkl": "bkl",
    "chutiya": "chutiya",
    "chutiye": "chutiye",
    "chutiya hai": "chutiya hai",
    "chutiya banaya": "chutiya banaya",
    "chutiya bana": "chutiya bana",
    "mc bc": "mc bc",
    "bhenchod": "bhenchod",
    "bhenchod hai": "bhenchod hai",
    "madarchod": "madarchod",
    "bhosdike": "bhosdike",
    "lund": "lund",
    "lund hai": "lund hai",
    "lund ka": "lund ka",
    "lund ke": "lund ke",
    "gand": "gand",
    "gandu": "gandu",
    "gand mara": "gand mara",
    "gand mare": "gand mare",
    
    # ---- Positive / aspirational terms ----
    "moti": "moti",
    "motivation": "motivation",
    "motivate": "motivate",
    "motivated": "motivated",
    "inspire": "inspire",
    "inspired": "inspired",
    "inspiration": "inspiration",
    "hope": "hope",
    "hopeful": "hopeful",
    "hoping": "hoping",
    "best": "best",
    "good luck": "good luck",
    "all the best": "all the best",
    "wishing": "wishing",
    "wish": "wish",
    "wishes": "wishes",
    "congratulations": "congratulations",
    "congrats": "congrats",
    "proud": "proud",
    "happy": "happy",
    "excited": "excited",
    "excitement": "excitement",
    "celebrate": "celebrate",
    "celebrating": "celebrating",
    "celebration": "celebration",
    "success": "success",
    "successful": "successful",
    "achieve": "achieve",
    "achievement": "achievement",
    "achieved": "achieved",
    
    # ---- Informational / advice terms ----
    "help": "help",
    "helped": "helped",
    "helping": "helping",
    "advice": "advice",
    "advise": "advise",
    "advised": "advised",
    "suggest": "suggest",
    "suggested": "suggested",
    "suggestion": "suggestion",
    "suggestions": "suggestions",
    "recommend": "recommend",
    "recommended": "recommended",
    "recommendation": "recommendation",
    "tip": "tip",
    "tips": "tips",
    "guide": "guide",
    "guidance": "guidance",
    "strategy": "strategy",
    "strategies": "strategies",
    "plan": "plan",
    "planning": "planning",
    "planned": "planned",
    "schedule": "schedule",
    "timetable": "timetable",
    "routine": "routine",
    "method": "method",
    "technique": "technique",
    "techniques": "techniques",
    "resource": "resource",
    "resources": "resources",
    "material": "material",
    "materials": "materials",
    "book": "book",
    "books": "books",
    "notes": "notes",
    "note": "note",
    "video": "video",
    "videos": "videos",
    "lecture": "lecture",
    "lectures": "lectures",
    "course": "course",
    "courses": "courses",
    "coaching": "coaching",
    "institute": "institute",
    "institutes": "institutes",
    
    # ---- Common typos / phonetic variations ----
    "baad": "baad",
    "baad me": "baad me",
    "baad mein": "baad mein",
    "pehle": "pehle",
    "phle": "pehle",
    "phele": "pehle",
    "phli": "pehli",
    "pehli": "pehli",
    "pahle": "pehle",
    "pahli": "pehli",
    "abhi": "abhi",
    "abhi tak": "abhi tak",
    "abhi bhi": "abhi bhi",
    "abhi nhi": "abhi nahi",
    "abhi se": "abhi se",
    "abhi ja": "abhi ja",
    "abhi aao": "abhi aao",
    "dekha": "dekha",
    "dekhi": "dekhi",
    "dekhe": "dekhe",
    "dekhna": "dekhna",
    "dekhne": "dekhne",
    "dekho": "dekho",
    "dekh": "dekh",
    "dikha": "dikha",
    "dikhi": "dikhi",
    "dikhe": "dikhe",
    "dikhao": "dikhao",
    "dikha de": "dikha de",
    "bata": "bata",
    "batao": "batao",
    "batana": "batana",
    "batane": "batane",
    "bata de": "bata de",
    "bata do": "bata do",
    "samajh": "samajh",
    "samajhna": "samajhna",
    "samajhne": "samajhne",
    "samajh aaya": "samajh aaya",
    "samajh aayi": "samajh aayi",
    "samajh aaye": "samajh aaye",
    "samajh nhi": "samajh nahi",
    "samajh nhi aaya": "samajh nahi aaya",
    "nhi samajh aaya": "nahi samajh aaya",
    "man": "man",
    "mann": "man",
    "man kar": "man kar",
    "man nhi": "man nahi",
    "man nhi kar": "man nahi kar",
    "man nhi raha": "man nahi raha",
    "man kiya": "man kiya",
    "man kare": "man kare",
    
    # ---- English-Hinglish hybrid (commonly used) ----
    "papa": "papa",
    "papa ne": "papa ne",
    "papa ko": "papa ko",
    "papa se": "papa se",
    "mummy": "mummy",
    "mummy ne": "mummy ne",
    "mummy ko": "mummy ko",
    "mummy se": "mummy se",
    "maa": "maa",
    "maa ne": "maa ne",
    "maa ko": "maa ko",
    "maa se": "maa se",
    "baap": "baap",
    "baap ne": "baap ne",
    "baap ko": "baap ko",
    "baap se": "baap se",
    "parents": "parents",
    "parent": "parent",
    "parental": "parental",
    "parental pressure": "parental pressure",
    "peer pressure": "peer pressure",
    "peer": "peer",
    "peers": "peers",
    "friend": "friend",
    "friends": "friends",
    "dost": "dost",
    "dost ne": "dost ne",
    "dost ko": "dost ko",
    "dost se": "dost se",
    "yaar": "yaar",
    "yaar ne": "yaar ne",
    "yaar ko": "yaar ko",
    "yaar se": "yaar se",
    "bhai": "bhai",
    "bhaiya": "bhaiya",
    "bhai ne": "bhai ne",
    "bhai ko": "bhai ko",
    "bhai se": "bhai se",
    "behen": "behen",
    "behen ne": "behen ne",
    "behen ko": "behen ko",
    "behen se": "behen se",
    "didi": "didi",
    "didi ne": "didi ne",
    "didi ko": "didi ko",
    "didi se": "didi se",
    
    # ---- Institutional / location terms ----
    "iit": "iit",
    "nit": "nit",
    "iiit": "iiit",
    "bits": "bits",
    "vit": "vit",
    "srm": "srm",
    "manipal": "manipal",
    "thapar": "thapar",
    "lnmiit": "lnmiit",
    "dtu": "dtu",
    "nsut": "nsut",
    "ipu": "ipu",
    "jnu": "jnu",
    "du": "du",
    "bhu": "bhu",
    "amu": "amu",
    "hyderabad": "hyderabad",
    "mumbai": "mumbai",
    "delhi": "delhi",
    "bangalore": "bangalore",
    "chennai": "chennai",
    "pune": "pune",
    "kolkata": "kolkata",
    "jaipur": "jaipur",
    "chandigarh": "chandigarh",
    "lucknow": "lucknow",
    "indore": "indore",
    "bhopal": "bhopal",
    "nagpur": "nagpur",
    "patna": "patna",
    "ranchi": "ranchi",
    "guwahati": "guwahati",
    
    # ---- DSA / tech prep terms (common in placement discussions) ----
    "dsa": "dsa",
    "leetcode": "leetcode",
    "codeforces": "codeforces",
    "codechef": "codechef",
    "hackerrank": "hackerrank",
    "hackerearth": "hackerearth",
    "gfg": "gfg",
    "geeksforgeeks": "geeksforgeeks",
    "interviewbit": "interviewbit",
    "striver": "striver",
    "love babbar": "love babbar",
    "dp": "dp",
    "graphs": "graphs",
    "tree": "tree",
    "trees": "trees",
    "array": "array",
    "arrays": "arrays",
    "string": "string",
    "strings": "strings",
    "linked list": "linked list",
    "linked lists": "linked lists",
    "stack": "stack",
    "stacks": "stacks",
    "queue": "queue",
    "queues": "queues",
    "heap": "heap",
    "heaps": "heaps",
    "hashmap": "hashmap",
    "hashmaps": "hashmaps",
    "map": "map",
    "maps": "maps",
    "set": "set",
    "sets": "sets",
    "vector": "vector",
    "vectors": "vectors",
    
    # ---- Miscellaneous common terms ----
    "acha": "acha",
    "accha": "acha",
    "theek": "theek",
    "thik": "theek",
    "thik hai": "thik hai",
    "theek hai": "theek hai",
    "sahi": "sahi",
    "sahi hai": "sahi hai",
    "sahi bola": "sahi bola",
    "galat": "galat",
    "galat hai": "galat hai",
    "galti": "galti",
    "galti se": "galti se",
    "galti ki": "galti ki",
    "galti ho gai": "galti ho gai",
    "galti ho gaya": "galti ho gaya",
    "bura": "bura",
    "bura hai": "bura hai",
    "bura lag": "bura lag",
    "bura laga": "bura laga",
    "bura lag rha": "bura lag raha",
    "bura lag rha hai": "bura lag raha hai",
    "khush": "khush",
    "khush hai": "khush hai",
    "khush ho": "khush ho",
    "khush hoon": "khush hoon",
    "khush raho": "khush raho",
    "dukh": "dukh",
    "dukh hai": "dukh hai",
    "dukh ho rha": "dukh ho raha",
    "dukh ho rha hai": "dukh ho raha hai",
    "dard": "dard",
    "dard hai": "dard hai",
    "dard ho rha": "dard ho raha",
    "dard ho rha hai": "dard ho raha hai",
    "kasht": "kasht",
    "kasht hai": "kasht hai",
    "musibat": "musibat",
    "musibat hai": "musibat hai",
    "musibat me": "musibat me",
    "musibat mein": "musibat mein",
    "problem": "problem",
    "problems": "problems",
    "issue": "issue",
    "issues": "issues",
    "solution": "solution",
    "solutions": "solutions",
    "answer": "answer",
    "answers": "answers",
    "question": "question",
    "questions": "questions",
    "doubt": "doubt",
    "doubts": "doubts",
    "clear": "clear",
    "clear hai": "clear hai",
    "clear nhi": "clear nahi",
    "confuse": "confuse",
    "confused": "confused",
    "confusion": "confusion",
    "confusion hai": "confusion hai",
    "samajh me nhi": "samajh me nahi",
    "samajh me nhi aaya": "samajh me nahi aaya",
    "samajh me nhi aayi": "samajh me nahi aayi",
    "samajh me nhi aaye": "samajh me nahi aaye",
    
    # ---- Temporal / frequency terms ----
    "roj": "roj",
    "roz": "roj",
    "daily": "daily",
    "har roz": "har roj",
    "har din": "har din",
    "din": "din",
    "dino": "dino",
    "dino se": "dino se",
    "dino tak": "dino tak",
    "raat": "raat",
    "raato": "raato",
    "raato se": "raato se",
    "raato tak": "raato tak",
    "subah": "subah",
    "subah se": "subah se",
    "subah tak": "subah tak",
    "shaam": "shaam",
    "shaam se": "shaam se",
    "shaam tak": "shaam tak",
    "mahine": "mahine",
    "mahino": "mahino",
    "mahino se": "mahino se",
    "mahino tak": "mahino tak",
    "saal": "saal",
    "saalo": "saalo",
    "saalo se": "saalo se",
    "saalo tak": "saalo tak",
    "sal": "saal",
    "salo": "saalo",
    "week": "week",
    "weeks": "weeks",
    "month": "month",
    "months": "months",
    "year": "year",
    "years": "years",
    "bar": "bar",
    "baar": "bar",
    "har bar": "har bar",
    "dobara": "dobara",
    "dubara": "dobara",
    "phir": "phir",
    "phir se": "phir se",
    "wapas": "wapas",
    "wapas se": "wapas se",
    "again": "again",
    "repeat": "repeat",
    "repeating": "repeating",
    "repeated": "repeated",
    
    # ---- Modality / hedging ----
    "shayad": "shayad",
    "sayad": "shayad",
    "shayad nhi": "shayad nahi",
    "shayad hai": "shayad hai",
    "lagta": "lagta",
    "lagti": "lagti",
    "lagte": "lagte",
    "lag rha": "lag raha",
    "lag rha hai": "lag raha hai",
    "lag rhi": "lag rahi",
    "lag rhi hai": "lag rahi hai",
    "lag rhe": "lag rahe",
    "lag rhe hai": "lag rahe hai",
    "lagta hai": "lagta hai",
    "lagti hai": "lagti hai",
    "lagte hai": "lagte hai",
    "mujhe lagta": "mujhe lagta",
    "mujhe lagti": "mujhe lagti",
    "mujhe lagte": "mujhe lagte",
    "mujhe lag rha": "mujhe lag raha",
    "mujhe lag rhi": "mujhe lag rahi",
    "mujhe lag rhe": "mujhe lag rahe",
    "lag rha hai": "lag raha hai",
    "lag rhi hai": "lag rahi hai",
    "lag rhe hai": "lag rahe hai",
    "ho sakta": "ho sakta",
    "ho sakti": "ho sakti",
    "ho sakte": "ho sakte",
    "ho saka": "ho saka",
    "ho saki": "ho saki",
    "ho sake": "ho sake",
    "nhi ho sakta": "nahi ho sakta",
    "nhi ho sakti": "nahi ho sakti",
    "nhi ho sakte": "nahi ho sakte",
    "ho gaya": "ho gaya",
    "ho gayi": "ho gayi",
    "ho gaye": "ho gaye",
    "ho jayega": "ho jayega",
    "ho jayegi": "ho jayegi",
    "ho jayenge": "ho jayenge",
    "ho jana": "ho jana",
    "ho jani": "ho jani",
    "ho jane": "ho jane",
    "ho gaya": "ho gaya",
    "ho gayi": "ho gayi",
    "ho gaye": "ho gaye",
    "ho jaao": "ho jaao",
    "ho jao": "ho jao",
}

# ============================================================================
# Derived lookup structures (computed at import time for performance)
# ============================================================================

# Set of all dictionary keys for fast membership testing
HINGLISH_DICT_KEYS: Set[str] = set(EXPANDED_HINGLISH_DICT.keys())

# Reverse lookup: canonical form -> list of variants
HINGLISH_DICT_REVERSE: Dict[str, List[str]] = {}
for k, v in EXPANDED_HINGLISH_DICT.items():
    HINGLISH_DICT_REVERSE.setdefault(v, []).append(k)

# Maximum key length for phrase-aware matching
MAX_DICT_KEY_LENGTH: int = max(len(k) for k in EXPANDED_HINGLISH_DICT.keys()) if EXPANDED_HINGLISH_DICT else 0

# ============================================================================
# Case-insensitive lookup wrapper
# ============================================================================

def normalize_word(word: str) -> str:
    """
    Normalize a single word using the expanded Hinglish dictionary.
    
    Case-insensitive lookup. If word not in dictionary, returns lowercase original.
    
    Parameters
    ----------
    word : str
        Word to normalize.
    
    Returns
    -------
    str
        Normalized canonical form (lowercase).
    """
    lower_word = word.lower().strip()
    return EXPANDED_HINGLISH_DICT.get(lower_word, lower_word)


def normalize_text(text: str) -> str:
    """
    Normalize a full text string by replacing each word with its canonical form.
    
    Simple whitespace tokenization. For phrase-aware tokenization,
    use phrase_tokenizer.py first, then this function.
    
    Parameters
    ----------
    text : str
        Text to normalize (should be pre-cleaned by artifact_remover).
    
    Returns
    -------
    str
        Normalized text with Hinglish words replaced by canonical forms.
    """
    words = text.split()
    normalized = [normalize_word(w) for w in words]
    return " ".join(normalized)


def get_variants(canonical: str) -> List[str]:
    """Return all known variants for a canonical form."""
    return HINGLISH_DICT_REVERSE.get(canonical, [])


# ============================================================================
# Validation / stats
# ============================================================================

def get_dict_stats() -> dict:
    """Return statistics about the expanded dictionary."""
    return {
        "total_entries": len(EXPANDED_HINGLISH_DICT),
        "unique_canonical_forms": len(HINGLISH_DICT_REVERSE),
        "max_key_length": MAX_DICT_KEY_LENGTH,
        "most_variant_canonical": max(
            HINGLISH_DICT_REVERSE.items(), key=lambda x: len(x[1])
        ) if HINGLISH_DICT_REVERSE else None,
        "sample_entries": list(EXPANDED_HINGLISH_DICT.items())[:10],
    }


if __name__ == "__main__":
    stats = get_dict_stats()
    print("=" * 60)
    print("EXPANDED HINGLISH DICTIONARY STATS")
    print("=" * 60)
    print(f"Total entries: {stats['total_entries']}")
    print(f"Unique canonical forms: {stats['unique_canonical_forms']}")
    print(f"Max key length: {stats['max_key_length']}")
    if stats['most_variant_canonical']:
        canonical, variants = stats['most_variant_canonical']
        print(f"Most variant canonical: '{canonical}' with {len(variants)} variants")
    print(f"\nSample entries:")
    for k, v in stats['sample_entries']:
        print(f"  {k:20} → {v}")
    
    # Quick test
    print("\n" + "=" * 60)
    print("QUICK TEST")
    print("=" * 60)
    test = "nhi kr rha tha kya kru jse koi tension nhi hai"
    print(f"BEFORE: {test}")
    print(f"AFTER:  {normalize_text(test)}")
